import { BaseProcessor } from "../base-worker/base.processor";
import { Job as BullJob } from "bullmq";
import { Injectable } from "@nestjs/common";
import { DataSource } from "typeorm";
import { InjectDataSource } from "@nestjs/typeorm";

import PDFDocument from "pdfkit";
import fs from "fs-extra";
import path from "path";
import { v4 as uuidv4 } from "uuid";
import { uploadFileLocal, uploadFileS3 } from "../media-worker/storageService";
import { table } from "console";

const MAX_ROWS = 1000;
const MAX_FILE_SIZE_MB = 20;
// const ALLOWED_TABLES = ["users", "orders", "products"];

@Injectable()
export class ReportProcessor extends BaseProcessor {
  constructor(@InjectDataSource() dataSource: DataSource) {
    super(dataSource);
  }
  protected async process(job: BullJob): Promise<void> {
    const payload = job.data.metadata;
    const tenantId = job.data.tenantId;
    const startTime = Date.now();

    // validation

    if (!payload.title) throw new Error("title is required");
    if (!payload.generatedBy) throw new Error("generatdBty is required");
    let reportData: any[] = payload.data || [];

    // Fetch DB data if queryConfig exists
    // if (payload.queryConfig) {
    //   const table = payload.queryConfig.table;
    //   const limit = payload.queryConfig.limit || 100;
    //   // if (!ALLOWED_TABLES.includes(table)) {
    //   //   throw new Error("Unauthorized table access");
    //   // }
    //   if (limit > MAX_ROWS) {
    //     throw new Error(`Max row limit is ${MAX_ROWS}`);
    //   }
    //   reportData = await this.dataSource.query(
    //     `SELECT * FROM ${table} LIMIT $1`,
    //     [limit],
    //   );
    // }
    // if (reportData.length > MAX_ROWS) {
    //   throw new Error(`Max data rows allowed: ${MAX_ROWS}`);
    // }

    // generate pdf

    const { fileName, filePath, pageCount } = await this.generatePDF(
      payload,
      reportData,
    );

    const stats = await fs.stat(filePath);

    if (stats.size > MAX_FILE_SIZE_MB * 1024 * 1024) {
      throw new Error("Generated PDF exceeds allowed size limit");
    }
    // upload file

    // upload to local first
    const localPath = await uploadFileLocal(filePath);

    // uploaed to s3
    let s3Path: string | null = null;

    if (process.env.USE_S3 === "true") {
      s3Path = await uploadFileS3(filePath, fileName);
    }
    // attach result to the job so that baseProcessor can persist metadata
    job.data.result = {
      local: localPath,
      s3: s3Path,
    };
    job.data.metadata = {
      ...job.data.metadata,
      report: {
        fileName,
        sizeBytes: stats.size,
        pageCount,
        rows: reportData.length,
        durationMs: Date.now() - startTime,
      },
    };
    // clean up temp files if needed
    if (process.env.CLEAN_TEMP_FILES === "true") {
      await fs.remove(filePath);
    }
  }

  private async generatePDF(payload: any, data: any[]) {
    const outputFileName = `${uuidv4()}.pdf`;
    const outputDir = path.join(
      process.cwd(),
      "processed_reports",
      outputFileName,
    );
    await fs.ensureDir(path.dirname(outputDir));

    return new Promise<{
      fileName: string;
      filePath: string;
      pageCount: number;
    }>((resolve, reject) => {
      const doc = new PDFDocument({ margin: 40 });
      const stream = fs.createWriteStream(outputDir);

      let pageCount = 1;

      doc.on("pageAdded", () => pageCount++);

      doc.pipe(stream);
      doc.fontSize(20).text(payload.title, { align: "center" });
      doc.moveDown();
      doc.fontSize(12).text(`Generated By: ${payload.generatedBy}`);
      doc.text(`Generated At : ${new Date().toISOString()}`);
      doc.moveDown();

      if (data.length === 0) {
        doc.text("No data available.");
      } else {
        data.forEach((row, index) => {
          doc.text(`${index + 1}. ${JSON.stringify(row)}`);
          doc.moveDown(0.5);
        });
      }
      doc.end();

      stream.on("finish", () =>
        resolve({ fileName: outputFileName, filePath: outputDir, pageCount }),
      );
      stream.on("error", reject);
    });
  }
}
