
services:
  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: jobque-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alerts.yml:/etc/prometheus/alerts.yml:ro
      - ./rules.yml:/etc/prometheus/rules.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=30d"
      - "--web.enable-lifecycle"

    networks:
      - jobque_default
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

  grafana:
    image: grafana/grafana:10.4.0
    container_name: jobque-grafana
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
    networks:
      - jobque_default
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: jobque-alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - ../secrets/slack_webhook:/run/secrets/slack_webhook:ro
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      # - ./monitoring/start-alertmanager.sh:/start.sh:ro
      - alertmanager_data:/alertmanager
    # entrypoint: ["/bin/sh", "/start.sh"]
    command: 
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--config.expand-env"
      - "--storage.path=/alertmanager"
      - "--web.external-url=http://localhost:9093"
    environment:
        - SMTP_USER=${SMTP_USER}
        - SMTP_PASS=${SMTP_PASS}
    networks:
      - jobque_default

volumes:
  prometheus_data:
  grafana_data:
  alertmanager_data:

networks:
  jobque_default:
    # driver: bridge
    external: true
    name: jobque_default