export enum JobStatus {
  QUEUED = "QUEUED",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  SCHEDULED = "SCHEDULED",
  SKIPPED = "SKIPPED",
  PENDING = "PENDING",
  WAITING_FOR_DEPENDENCIES = "WAITING_FOR_DEPENDENCIES",
  READY = "READY",
  STAGED = "STAGED",
}
