apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../

patches:
  - path: pull-policy-patch.yaml
  - path: media-worker-replicas.yaml

images:
  - name: ghcr.io/basanta1-github/orchestrate-api
    newName: ghcr.io/basanta1-github/orchestrate-api
    newTag: latest
  - name: ghcr.io/basanta1-github/orchestrate-worker
    newName: ghcr.io/basanta1-github/orchestrate-worker
    newTag: latest
