apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: orchestrate
spec:
  template:
    spec:
      containers:
        - name: api
          imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-worker
  namespace: orchestrate
spec:
  template:
    spec:
      containers:
        - name: worker
          imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-worker
  namespace: orchestrate
spec:
  template:
    spec:
      containers:
        - name: worker
          imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-worker
  namespace: orchestrate
spec:
  template:
    spec:
      containers:
        - name: worker
          imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etl-worker
  namespace: orchestrate
spec:
  template:
    spec:
      containers:
        - name: worker
          imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-worker
  namespace: orchestrate
spec:
  template:
    spec:
      containers:
        - name: worker
          imagePullPolicy: IfNotPresent
